/* SPDX-License-Identifier: MIT
 *
 * Copyright © 2024 Intel Corporation
 */

#ifndef GHE_H_
#define GHE_H_

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

#define GLOBALHIST_BIN_COUNT 32   // Total number of segments in GlobalHist
#define GLOBALHIST_IET_LUT_LENGTH 33 // Total number of IET entries

enum pipe_id {
	GlobalHist_PIPE_A = 0,
	GlobalHist_PIPE_B = 1,
	GlobalHist_PIPE_C = 2,
	GlobalHist_PIPE_D = 3
};

/**
 * struct globalhist_args - histogram and iet arguments
 *
 * @pipeid: pipe on which the histogram is fetched
 * @isprogramdiet:
 * @histogrammode: histogram mode(mac(RGB), YUV, programmable co-efficient, etc)
 * @binscount: number of bins in the histogram
 * @ietmode: mode in which the LUT values are provided by the algorithm.
 * @ietlutentries: number of LUT entries supported by the hardware.
 * @dietfactor: address at which the LUT entries generated by the algorithm are stored
 * @histogram: address at which the histogram generated by the hardware are stored
 * @resolution_x:
 * @resolution_y:
 */
struct globalhist_args {
	enum pipe_id pipeid;
	bool isprogramdiet;
	uint8_t histogrammode;
	uint32_t binscount;
	uint8_t ietmode;
	uint32_t ietlutentries;
	uint64_t dietfactor;
	uint64_t histogram;
	uint32_t resolution_x;
	uint32_t resolution_y;
};

void histogram_compute_generate_data_bin(struct globalhist_args *gheargs);
#endif
